[package]
name = "discord_tts_bot"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"

[dependencies]
serde = "1"
regex = "1"
rand = "0.8"
toml = "0.5"
anyhow = "1"
sha2 = "0.10"
strfmt = "0.1"
indexmap = "1"
tracing = "0.1"
linkify = "0.8"
strsim = "0.10"
reqwest = "0.11"
sysinfo = "0.23"
lazy_static = "1"
itertools = "0.10"
num-format = "0.4"
parking_lot = "0.12"
generic-array = "0.14"
deadpool-postgres = "0.10"
#serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", default-features = false, features = ["simdjson"] }

[dependencies.postgres-types]
version = "0.2"
features = ["derive"]

[dependencies.dashmap]
version = "5"
default-features = false

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "signal", "parking_lot"]

[dependencies.poise]
git = "https://github.com/kangalioo/poise"
rev = "953f863992ef9f49889be91e108f24ef4a9d1873"

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"

[dependencies.lavalink-rs]
git = "https://gitlab.com/GnomedDev/lavalink-rs"
rev = "325956eee7078fb4779c2cf1b4ab6aa53d6c2c22"
features = ["serenity", "rustls"]


# lavalink pulls serenity from crates.io. tell it to pull from github instead 
[patch.crates-io]
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
songbird = { git = "https://github.com/serenity-rs/songbird", branch = "next" }
