[package]
name = "discord_tts_bot"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"

[dependencies]
regex = "1"
rand = "0.8"
toml = "0.5"
dashmap = "5"
strfmt = "0.1"
indexmap = "1"
tracing = "0.1"
strsim = "0.10"
reqwest = "0.11"
cargo-lock = "7"
lazy_static = "1"
itertools = "0.10"
parking_lot = "0.12"
deadpool-postgres = "0.10"
#serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", default-features = false, features = ["simdjson"] }

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "signal", "parking_lot"]

[dependencies.poise]
git = "https://github.com/kangalioo/poise"
features = ["collector"]
branch = "develop"

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"

[dependencies.lavalink-rs]
git = "https://gitlab.com/vicky5124/lavalink-rs"
features = ["serenity", "rustls"]

[dependencies.psutil]
version = "3"
features = ["process"]
default-features = false

# Premium dependencies
[dependencies.base64]
version = "0.13"
optional = true

[dependencies.serde]
version = "1"
optional = true

[dependencies.jsonwebtoken]
version = "7"
optional = true


# lavalink pulls serenity from crates.io. tell it to pull from github instead 
[patch.crates-io]
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
songbird = { git = "https://github.com/serenity-rs/songbird", branch = "next" }

[features]
premium = ["base64", "serde", "jsonwebtoken"]
