services:
    bot:
        build: .
        volumes:
          - type: bind
            source: ./config.toml
            target: /config.toml
        depends_on: [database, lavalink]
    lavalink:
        image: fredboat/lavalink:dev
        volumes:
          - type: bind
            source: ./lavalink_config.yml
            target: /opt/Lavalink/application.yml

        expose: [2333]
    database:
        image: postgres:13
        expose: [5432]
        environment: 
            POSTGRES_USER: tts
            POSTGRES_PASSWORD: tts_password
    tts-service:
        build:
          context: git://github.com/GnomedDev/tts-service.git
          args:
              MODES: "espeak,gtts"

        environment:
          -  IPV6_BLOCK
          -  LOG_LEVEL=INFO
          -  BIND_ADDR=0.0.0.0:20310
        network_mode: "host"
        expose: [20310]
