services:
    bot:
        build: .
        volumes:
          - type: bind
            source: ./config.toml
            target: /config.toml
        depends_on: [database, lavalink]
    lavalink:
        image: fredboat/lavalink:dev
        volumes:
          - type: bind
            source: ./lavalink_config.yml
            target: /opt/Lavalink/application.yml
          - type: bind
            source: ./lavalink-plugins
            target: /opt/Lavalink/plugins
        expose: [2333]
    database:
        image: postgres:13
        expose: [5432]
        environment: 
            POSTGRES_USER: tts
            POSTGRES_PASSWORD: tts_password
    gtts-service:
        build: git://github.com/GnomedDev/gtts-service.git
        network_mode: "host"
        expose: [20310]

        environment:
          -  LOG_LEVEL=INFO
          -  BIND_ADDR=0.0.0.0:20310
          -  IPV6_BLOCK=$(IPV6_BLOCK)
