services:
    bot:
        build: .
        volumes:
          - type: bind
            source: ./config.toml
            target: /config.toml

        depends_on: [database, lavalink, tts-service]
        network_mode: "host"
    lavalink:
        image: fredboat/lavalink:dev
        volumes:
          - type: bind
            source: ./lavalink_config.yml
            target: /opt/Lavalink/application.yml

        network_mode: "host"
        expose: [2333]
    database:
        image: postgres:13
        ports: [5432:5432]
        environment: 
            POSTGRES_USER: tts
            POSTGRES_PASSWORD: tts_password
    tts-service:
        build: gnomeddev/tts-service
        volumes:
          - type: bind
            source: ${GOOGLE_APPLICATION_CREDENTIALS}
            target: /gcp.json
        environment:
          -  IPV6_BLOCK
          -  LOG_LEVEL=INFO
          -  BIND_ADDR=0.0.0.0:20310
          -  GOOGLE_APPLICATION_CREDENTIALS=/gcp.json
        network_mode: "host"
        expose: [20310]
